### ISSUE TITLE
Credentials Test Failing Randomly

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-extractor-mysql#15]
![image](https://user-images.githubusercontent.com/497675/31126800-19ce746a-a84d-11e7-8b35-5dbc2ea0f30e.png)

Vypadá to, že to je závislé na instanci, jediná, která to povolí, je `kbc-us-east-1-syrup-docker-i-003ff9a4132cd2956`.

**Comment by ondrejhlavacek** [comment]
Bude to asi nějaký nastavení subnetu/networku, Snowflake nebo MySQL na RDS takový problémy nemá.

**Comment by kacurez** [comment]
nieco podobne som skusal minuly tyzden a tiez mi neslo, nakoniec mi Martin poradil zadata ip namiesto url a to zistit cez:
`dig ANY ec2-34-228...compute-1.amaznoaws.com`
sice neviem ci to je rovnaky pripad..

**Comment by ondrejhlavacek** [comment]
Byla restartovaná instance, vypnul jsem jí, nahodila se nová a vše OK.

https://keboola.slack.com/archives/C31U6BGJC/p1507036513000327
