### ISSUE TITLE
"Query returned empty result" via mysql has gone away. should it be an error? retry?

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-mysql#46]
It came through as an Application error for some reason :-( https://keboola.slack.com/archives/C09U3R1J4/p1527138787000014

**Comment by pivnicek** [comment]
![mysqlerror](https://user-images.githubusercontent.com/569139/40475136-174c8aaa-5f41-11e8-9a21-83dac6d16f4a.png)

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1528157886000131 again

**Comment by pivnicek** [comment]
again:( https://keboola.slack.com/archives/C09U3R1J4/p1533248050000033

**Comment by Halama** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1534371369000100

**Comment by kacurez** [comment]
co to vlastne znamena? ze to db server nedal a odpojil sa alebo ta query skutocne vratila prazdne data? Inac pisal dalsi klient na zendesk takze by bolo dobre to nejak fixnut.

**Comment by kacurez** [comment]
este v logu jobu vidim ze to nejaky retry skusilo
![image](https://user-images.githubusercontent.com/1412120/44204392-a73d4200-a152-11e8-8e56-89242e35954d.png)

**Comment by ErikZigo** [comment]
No jeste to muze byt treba timeoutem VPN, ale to by jim delalo porad po stejny dobe.

**Comment by pivnicek** [comment]
So what is happening here is that it hits \ErrorException on the old `Empty row packet body.` and then retries and gets `mysql has gone away`, which it doesn't retry, but should

**Comment by odinuv** [comment]
another one https://papertrailapp.com/groups/23635/events?focus=971129224817680385&q=9eee5cf081dcb929f184ad56bd341600&selected=971129224817680385

**Comment by pivnicek** [comment]
here's one where it hits `empty row packet body` and retries and the extractor thinks everything is ok but the result is missing 1/3 of the expected output:
https://keboola.zendesk.com/agent/tickets/9114

**Comment by ondrejhlavacek** [comment]
> Mám dojem, že se kvuli tomu nestahly všechny data a zjištuji jestli je chyba u nas v DB nebo neco na chvilku vypadlo u vas.
> Našel jsem k tomu tohle MySQL nastaveni, že by mohlo být duvodem "net_read_timeout"

**Comment by ondrejhlavacek** [comment]
For now i'd skip retry for `empty row packet body` before it gets fixed properly.

**Comment by MiroCillik** [comment]
It's weird that the retry didn't downloaded all the data :/ Could be maybe something with MySQL internal cursor behaviour..

Looking into code. What about the `@` suppressors that were they before? They're no longer needed?
https://github.com/keboola/db-extractor-common/commit/41007d32a941d0af393e51c956b685b591625825

Also, it would be great to confirm, that this issues are not caused by VPN timeout.

**Comment by odinuv** [comment]
omg, how did the @ got there again?

**Comment by pivnicek** [comment]
We definitely removed all those.

**Comment by MiroCillik** [comment]
Well, I don't know. It was there because the PDO doesn't only throw exception but also produced a warning or something like that? I'm not sure, that's why I'm asking.

**Comment by pivnicek** [comment]
Yes, it produces an `ErrorException` but those are being retried now.

**Comment by odinuv** [comment]
if it's there it produces a warning and that gets hidden, so it continues without error. If it is not there the warning gets converted by error hander to exception and should be retried

**Comment by odinuv** [comment]
i'll probably try the retry under debugger

**Comment by odinuv** [comment]
i managed to do it once - the extractor wrote that it finished successfully and didn't download all the data. The problem is - i have no idea how - but it seems it's really possible :(

**Comment by odinuv** [comment]
braindump: ok, got it - it's real hard on docker images, but not that difficult with RDS. When the connection is lost during fetch, the fetch is retried, but the $stmt cursor is no longer valid and so fetch returns false (no ex or warning) - i.e. for retry during fetch, the query has to be re-executed (and the csv file deleted).

**Comment by pivnicek** [comment]
omg, that makes sense.

**Comment by ondrejhlavacek** [comment]
Not sure about ETA, but current state is not acceptable - returning incomplete data and successful job. Can this throw a user exception before it gets fixed?

**Comment by pivnicek** [comment]
@ondrejhlavacek fix is here https://github.com/keboola/db-extractor-common/pull/71.  Will hopefully release today.

**Comment by ondrejhlavacek** [comment]
okay, thanks!
