### ISSUE TITLE
Undefined index "autoIncrement"

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-mysql#71]
![screenshot_2018-09-17_15-23-52](https://user-images.githubusercontent.com/419849/45625808-17125580-ba8e-11e8-8bd5-a833129a13b4.png)

**Comment by ujovlado** [comment]
Btw, this should be fatal 500 - so we are able to detect it.

**Comment by ujovlado** [comment]
Also, after fix of this err, the check for incremental loading will be necessary - since we don't know the value of auto_increment column.

**Comment by pivnicek** [comment]
@ujovlado 

> Also, after fix of this err, the check for incremental loading will be necessary - since we don't know the value of auto_increment column.

do you mean in the UI?

**Comment by ujovlado** [comment]
No, I meant `validateIncrementalFetching`. Since auto_increment won't be available, the only remaining optioon is timestamp column, right?

**Comment by pivnicek** [comment]
Ah, you mean that we should check if the table `autoIncrement` value is set here https://github.com/keboola/db-extractor-mysql/blob/master/src/Keboola/DbExtractor/Extractor/MySQL.php#L292  and if not should not allow that column for incremental fetching.

Yes, that's true.  If we all the column here, and they choose it on the front-end, it will break when the front end does not find the value.  I'll make a follow-up issue.  Thanks @ujovlado

**Comment by ujovlado** [comment]
Yep, something like that - we now it has auto increment, but value is unknown to us. ;)
