### ISSUE TITLE
ErrorException:Undefined index: name

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-mysql#86]
https://connection.keboola.com/admin/utils/logs?file=2018/10/25/13/2018-10-25-13-57-45-5bd1afb962d63-exception

```
{
  "errFile": "/code/src/Keboola/DbExtractor/Extractor/MySQL.php",
  "errLine": 143,
  "errCode": 0,
  "errTrace": "#0 /code/src/Keboola/DbExtractor/Extractor/MySQL.php(143): Keboola\\DbExtractor\\Application::Keboola\\DbExtractor\\{closure}(8, 'Undefined index...', '/code/src/Keboo...', 143, Array)\n#1 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\\DbExtractor\\Extractor\\MySQL->export(Array)\n#2 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#3 /code/src/run.php(63): Keboola\\DbExtractor\\Application->run()\n#4 {main}",
  "errPrevious": ""
}
```

**Comment by Halama** [comment]
It is in exception message https://github.com/keboola/db-extractor-mysql/blob/31915c1a04429b663966a110a02250be14150291/src/Keboola/DbExtractor/Extractor/MySQL.php#L143

**Comment by pivnicek** [comment]
FYI: This is related to https://github.com/keboola/db-extractor-mysql/issues/27

This exception is (supposed to be thrown) when the database in the connection configuration doesn't match the selected schema of the selected table.  This will happen when they change the database name on their end, then the recorded schemas for the rows won't match the DB and the table will need to be re-selected.
